# Generated by Django 4.1.7 on 2023-04-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientdb_delete_patientdb2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patientdb',
            new_name='Patientdb3',
        ),
    ]
