# Generated by Django 4.1.7 on 2023-04-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_patientdb3_patientdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdb',
            name='pimage',
            field=models.ImageField(upload_to=''),
        ),
    ]
